### ISSUE TITLE
Size of key error?

### ISSUE THREAD

**Issue by rudak** [vmelnik-ukraine/DoctrineEncryptBundle#23]
here is my error and i dont know how to solve it :(

ContextErrorException: Warning: mcrypt_encrypt(): Size of key is too large for this algorithm in **path/vendor/vmelnik/doctrine-encrypt-bundle/VMelnik/DoctrineEncryptBundle/Encryptors/AES256Encryptor.php line 34

thank you very much

**Comment by numediaweb** [comment]
I still have this issue:
Warning: mcrypt_encrypt(): Size of key is too large for this algorithm
`in vendor\vmelnik\doctrine-encrypt-bundle\VMelnik\DoctrineEncryptBundle\Encryptors\AES256Encryptor.php at line 34`

**Comment by vmelnik-ukraine** [comment]
Hi @numediaweb. Could you please provide more details, maybe a secret key that is `similar` to yours? As was mentioned in the previous comment, you should be able to use a key of any size because in `AES256Encryptor`'s `__construct` I apply md5 to a secret key:

``` php
// VMelnik/DoctrineEncryptBundle/Encryptors/AES256Encryptor.php
//...

public function __construct($key) {
    $this->secretKey = md5($key);
    // ...
}
```

Also, please check if you use the version with the fix or an older one.
